name: Store Submission
description: 'Submit the app to app stores'
inputs:
  environment:
    required: true
    description: 'The environment to submit for'
  platform:
    required: true
    description: 'The platform to build for'

runs:
  using: composite
  steps:
    - name: Get latest build
      id: latest_build
      run: |
        BUILD_ID=$(eas build:list --platform ios --profile ${{ inputs.environment }} --non-interactive --json | jq -r '.[0].id')
        echo "build_id=$BUILD_ID" >> $GITHUB_OUTPUT
      shell: bash

    - name: Print eas file
      run: cat eas.json
      shell: bash

    - name: Submit to Stores
      run: |
        eas submit --platform ${{ inputs.platform }} --profile ${{ inputs.environment }} --non-interactive --id ${{ steps.latest_build.outputs.build_id }}
      shell: bash
