name: 'Update EAS JSON'
description: 'Updates eas.json with environment-specific variables'
inputs:
  environment:
    description: 'Environment (e.g. production, staging)'
    required: true
  version:
    description: 'App version'
    required: true
  vars:
    description: 'JSON string of variables'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Update eas.json
      shell: bash
      run: |
        jq --arg env "${{ inputs.environment }}" \
           --arg version "${{ inputs.version }}" \
           --argjson vars '${{ inputs.vars }}' \
        '.build[$env].env += ($vars | with_entries(select(.key | startswith("EXPO_PUBLIC_"))))
         | .build[$env].env += {
           "EXPO_PUBLIC_APP_ENV": $env,
           "EXPO_PUBLIC_APP_VERSION": $version
         }' eas.json > eas.json.tmp && mv eas.json.tmp eas.json
        echo "Updated eas.json:"
