name: OTA Update
description: 'Perform an OTA update'
inputs:
  channel:
    required: true
    description: 'The environment to update'
  version:
    required: true
    description: 'The version number'
  build_number:
    required: true
    description: 'The build number'
runs:
  using: composite
  steps:
    - name: Set environment variables
      shell: bash
      run: |
        echo "EXPO_PUBLIC_APP_VERSION=${{ inputs.version }}" >> $GITHUB_ENV
        echo "EXPO_PUBLIC_BUILD_NUMBER=${{ inputs.build_number }}" >> $GITHUB_ENV

    - name: Perform OTA Update
      shell: bash
      run: |
        eas update --channel ${{ inputs.channel }} \
          --message "Update ${{ inputs.channel }} to ${{ inputs.version }} (build ${{ inputs.build_number }})"
