name: 'Increment Build Number'
description: 'Increments the build number or sets it to 1 if not present'
inputs:
  gh_token:
    description: 'GitHub token for authentication'
    required: true
  current_build_number:
    description: 'The current build number'
    required: false
    default: '0'
outputs:
  build_number:
    description: 'The incremented build number'
    value: ${{ steps.increment.outputs.build_number }}

runs:
  using: 'composite'
  steps:
    - name: Increment build number
      id: increment
      shell: bash
      run: |
        if [[ -z "${{ inputs.current_build_number }}" || "${{ inputs.current_build_number }}" == "0" ]]; then
          build_number=1
        else
          build_number=$((${{ inputs.current_build_number }} + 1))
        fi
        gh variable set BUILD_NUMBER -b "${build_number}"
        echo "build_number=${build_number}" >> $GITHUB_OUTPUT
      env:
        GH_TOKEN: ${{ inputs.gh_token }}
