name: Version Management
description: 'Manage version'
inputs:
  version_bump:
    required: true
    description: 'Type of version bump'
  increment:
    required: true
    description: 'Whether to increment the version'
outputs:
  version:
    description: 'The version number'
    value: ${{ steps.version_management.outputs.version }}
runs:
  using: composite
  steps:
    - name: Version Management
      id: version_management
      run: |
        CURRENT_VERSION=$(node -p "require('./package.json').version")

        if [[ "${{ inputs.increment }}" == "true" && "${{ inputs.version_bump }}" != "none" ]]; then
          git config user.name github-actions
          git config user.email github-actions@github.com
          npm version ${{ inputs.version_bump }} -m "Bump version to %s" --no-git-tag-version
          NEW_VERSION=$(node -p "require('./package.json').version")
        else
          NEW_VERSION=$CURRENT_VERSION
        fi

        echo "version=${NEW_VERSION}" >> $GITHUB_OUTPUT
      shell: bash
