name: Hotfix Release
on:
  workflow_dispatch:
    inputs:
      action_type:
        description: 'Action Type'
        required: true
        type: choice
        options:
          - build_and_submit
          # - ota_update
      platform:
        description: 'Platform'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android

jobs:
  hotfix-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Version Management
        uses: ./.github/actions/version
        id: version
        with:
          version_bump: 'none'
          increment: false

      - name: Build and Submit
        if: github.event.inputs.action_type == 'build_and_submit'
        uses: ./.github/actions/build
        with:
          environment: production
          platform: ${{ github.event.inputs.platform }}
          auto_submit: true

      - name: OTA Update
        if: github.event.inputs.action_type == 'ota_update'
        uses: ./.github/actions/ota-update
        env:
          VARS: ${{ toJson(vars) }}
        with:
          channel: production
          version: ${{ steps.version.outputs.version }}

      - name: Create hotfix tag
        uses: ./.github/actions/create-hotfix-tag
        id: hotfix_tag
        with:
          version: ${{ steps.version.outputs.version }}
