name: Production Submit

on:
  workflow_dispatch:
    inputs:
      platform:
        description: 'Platform'
        required: true
        default: 'all'
        type: choice
        options:
          - all
          - ios
          - android

jobs:
  production-release:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Environment
        uses: ./.github/actions/setup
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Version Management
        uses: ./.github/actions/version
        id: version
        with:
          version_bump: 'none'
          increment: false

      - name: Build and Submit
        uses: ./.github/actions/build
        with:
          environment: production
          platform: ${{ github.event.inputs.platform }}
          auto_submit: true
# Uncomment and add your slack webhook url to send Slack notification after the build is submitted
#      - name: Send Slack Notification
#        id: slack
#        uses: slackapi/slack-github-action@v1.26.0
#        with:
#          payload: |
#            {
#              "version": "${{ steps.version.outputs.version }}"
#            }
#        env:
#          SLACK_WEBHOOK_URL: https://hooks.slack.com/triggers/**
